FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o email_service .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/email_service .

EXPOSE 3003

CMD ["./email_service"]