version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_eLearning
    ports:
      - "6381:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data

volumes:
  redis_data: