// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: gRPC/gRPC_Code/CourseProgress/course_progress.proto

package CourseProgress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseProgressRequest) Reset() {
	*x = CourseProgressRequest{}
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseProgressRequest) ProtoMessage() {}

func (x *CourseProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseProgressRequest.ProtoReflect.Descriptor instead.
func (*CourseProgressRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescGZIP(), []int{0}
}

func (x *CourseProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CourseProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CourseProgressResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CourseProgressData *CourseProgression     `protobuf:"bytes,1,opt,name=courseProgressData,proto3" json:"courseProgressData,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CourseProgressResponse) Reset() {
	*x = CourseProgressResponse{}
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseProgressResponse) ProtoMessage() {}

func (x *CourseProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseProgressResponse.ProtoReflect.Descriptor instead.
func (*CourseProgressResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescGZIP(), []int{1}
}

func (x *CourseProgressResponse) GetCourseProgressData() *CourseProgression {
	if x != nil {
		return x.CourseProgressData
	}
	return nil
}

type CourseProgression struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgressPercent *int32                 `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3,oneof" json:"progress_percent,omitempty"`
	IsCompleted     *bool                  `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3,oneof" json:"is_completed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CourseProgression) Reset() {
	*x = CourseProgression{}
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseProgression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseProgression) ProtoMessage() {}

func (x *CourseProgression) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseProgression.ProtoReflect.Descriptor instead.
func (*CourseProgression) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescGZIP(), []int{2}
}

func (x *CourseProgression) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseProgression) GetProgressPercent() int32 {
	if x != nil && x.ProgressPercent != nil {
		return *x.ProgressPercent
	}
	return 0
}

func (x *CourseProgression) GetIsCompleted() bool {
	if x != nil && x.IsCompleted != nil {
		return *x.IsCompleted
	}
	return false
}

var File_gRPC_gRPC_Code_CourseProgress_course_progress_proto protoreflect.FileDescriptor

const file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDesc = "" +
	"\n" +
	"3gRPC/gRPC_Code/CourseProgress/course_progress.proto\x12\x0eCourseProgress\"K\n" +
	"\x15CourseProgressRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\tR\bcourseId\"k\n" +
	"\x16CourseProgressResponse\x12Q\n" +
	"\x12courseProgressData\x18\x01 \x01(\v2!.CourseProgress.CourseProgressionR\x12courseProgressData\"\xa1\x01\n" +
	"\x11CourseProgression\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x10progress_percent\x18\x02 \x01(\x05H\x00R\x0fprogressPercent\x88\x01\x01\x12&\n" +
	"\fis_completed\x18\x03 \x01(\bH\x01R\visCompleted\x88\x01\x01B\x13\n" +
	"\x11_progress_percentB\x0f\n" +
	"\r_is_completed2{\n" +
	"\x15CourseProgressService\x12b\n" +
	"\x11GetCourseProgress\x12%.CourseProgress.CourseProgressRequest\x1a&.CourseProgress.CourseProgressResponseB>Z<Quiz_service_go/gRPC/gRPC_Code/CourseProgress;CourseProgressb\x06proto3"

var (
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescOnce sync.Once
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescData []byte
)

func file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescGZIP() []byte {
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescOnce.Do(func() {
		file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDesc), len(file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDesc)))
	})
	return file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDescData
}

var file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_goTypes = []any{
	(*CourseProgressRequest)(nil),  // 0: CourseProgress.CourseProgressRequest
	(*CourseProgressResponse)(nil), // 1: CourseProgress.CourseProgressResponse
	(*CourseProgression)(nil),      // 2: CourseProgress.CourseProgression
}
var file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_depIdxs = []int32{
	2, // 0: CourseProgress.CourseProgressResponse.courseProgressData:type_name -> CourseProgress.CourseProgression
	0, // 1: CourseProgress.CourseProgressService.GetCourseProgress:input_type -> CourseProgress.CourseProgressRequest
	1, // 2: CourseProgress.CourseProgressService.GetCourseProgress:output_type -> CourseProgress.CourseProgressResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_init() }
func file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_init() {
	if File_gRPC_gRPC_Code_CourseProgress_course_progress_proto != nil {
		return
	}
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDesc), len(file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_goTypes,
		DependencyIndexes: file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_depIdxs,
		MessageInfos:      file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_msgTypes,
	}.Build()
	File_gRPC_gRPC_Code_CourseProgress_course_progress_proto = out.File
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_goTypes = nil
	file_gRPC_gRPC_Code_CourseProgress_course_progress_proto_depIdxs = nil
}
