// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: gRPC/gRPC_Code/CourseProgress/course_progress.proto

package CourseProgress

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseProgressService_GetCourseProgress_FullMethodName = "/CourseProgress.CourseProgressService/GetCourseProgress"
)

// CourseProgressServiceClient is the client API for CourseProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseProgressServiceClient interface {
	GetCourseProgress(ctx context.Context, in *CourseProgressRequest, opts ...grpc.CallOption) (*CourseProgressResponse, error)
}

type courseProgressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseProgressServiceClient(cc grpc.ClientConnInterface) CourseProgressServiceClient {
	return &courseProgressServiceClient{cc}
}

func (c *courseProgressServiceClient) GetCourseProgress(ctx context.Context, in *CourseProgressRequest, opts ...grpc.CallOption) (*CourseProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseProgressResponse)
	err := c.cc.Invoke(ctx, CourseProgressService_GetCourseProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseProgressServiceServer is the server API for CourseProgressService service.
// All implementations must embed UnimplementedCourseProgressServiceServer
// for forward compatibility.
type CourseProgressServiceServer interface {
	GetCourseProgress(context.Context, *CourseProgressRequest) (*CourseProgressResponse, error)
	mustEmbedUnimplementedCourseProgressServiceServer()
}

// UnimplementedCourseProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseProgressServiceServer struct{}

func (UnimplementedCourseProgressServiceServer) GetCourseProgress(context.Context, *CourseProgressRequest) (*CourseProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseProgress not implemented")
}
func (UnimplementedCourseProgressServiceServer) mustEmbedUnimplementedCourseProgressServiceServer() {}
func (UnimplementedCourseProgressServiceServer) testEmbeddedByValue()                               {}

// UnsafeCourseProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseProgressServiceServer will
// result in compilation errors.
type UnsafeCourseProgressServiceServer interface {
	mustEmbedUnimplementedCourseProgressServiceServer()
}

func RegisterCourseProgressServiceServer(s grpc.ServiceRegistrar, srv CourseProgressServiceServer) {
	// If the following call pancis, it indicates UnimplementedCourseProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseProgressService_ServiceDesc, srv)
}

func _CourseProgressService_GetCourseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseProgressServiceServer).GetCourseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseProgressService_GetCourseProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseProgressServiceServer).GetCourseProgress(ctx, req.(*CourseProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseProgressService_ServiceDesc is the grpc.ServiceDesc for CourseProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CourseProgress.CourseProgressService",
	HandlerType: (*CourseProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourseProgress",
			Handler:    _CourseProgressService_GetCourseProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/gRPC_Code/CourseProgress/course_progress.proto",
}
