# Number Of Worker Process
worker_processes 1;

env JWT_SECRET;

events {
    # How many concurrent process 1 worker should have
    worker_connections 1024; 
}

http {
    # Will Not Send Any Nginx Related Data To Response Headers
    server_tokens off;
    include mime.types;
    default_type application/octet-stream;

    limit_req_zone $binary_remote_addr zone=eLearningRateLimit:10m rate=100r/m;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    access_log  /var/log/nginx/access.log  main;
    # Specifies the file and format for access logs.

    error_log   /var/log/nginx/error.log warn;

    sendfile on;
    client_max_body_size 500M;
    keepalive_timeout 65;

    lua_package_path "/usr/local/openresty/lualib/?.lua;;";

    include /etc/nginx/conf.d/*.conf;
}