FROM node:20-alpine AS base

WORKDIR /app

RUN npm i -g pnpm 

ENV PNPM_HOME="/root/.pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN pnpm i -g typescript

RUN pnpm i -g ts-node

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY Auth_service/package.json ./Auth_service/package.json
COPY shared-middleware/package.json ./shared-middleware/package.json

RUN pnpm install --filter auth_services...

FROM base AS build

WORKDIR /app

COPY Auth_service ./Auth_service

COPY shared-middleware ./shared-middleware

RUN pnpm --filter shared-middleware build && pnpm --filter auth_services build

FROM node:20-alpine AS runner
WORKDIR /app

RUN npm i -g pnpm

COPY --from=build /app/Auth_service ./Auth_service
COPY --from=build /app/shared-middleware ./shared-middleware
COPY --from=build /app/node_modules ./node_modules


WORKDIR /app/Auth_service

# CMD [ "pnpm", "start" ] 
CMD ["sh", "-c", "sleep 3600"]