FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY Auth_service/package.json ./Auth_service/package.json
COPY shared-middleware/package.json ./shared-middleware/package.json

RUN npm i -g pnpm && pnpm install --filter auth_services

COPY Auth_service ./Auth_service

COPY shared-middleware ./shared-middleware

WORKDIR /app/Auth_service

CMD [ "pnpm", "start" ]