FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY Progression_service_GO/go.mod Progression_service_GO/go.sum ./

RUN go mod download

COPY Progression_service_GO .

RUN go build -o progression_service .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/progression_service .

EXPOSE 3003

CMD ["./progression_service"]