FROM golang:1.24.5-alpine AS builder

RUN apk --no-cache add git ca-certificates curl && update-ca-certificates

WORKDIR /app

ENV GOPROXY=direct

COPY ./go.mod ./go.sum ./

# RUN go mod download

COPY . .

# RUN go build -o progression_service .

FROM alpine:latest

WORKDIR /app

# COPY --from=builder /app/progression_service .

EXPOSE 3003

# CMD ["./progression_service"]