FROM golang:1.24.5-alpine AS builder

RUN apk --no-cache add git ca-certificates curl && update-ca-certificates

WORKDIR /app

ENV GOPROXY=direct

COPY go.mod go.sum ./

RUN touch test.txt

RUN go mod download

COPY . .

RUN go build -o quiz_service .

FROM alpine:latest

WORKDIR /app

RUN touch test.txt

COPY --from=builder /app/quiz_service .

EXPOSE 3003

CMD ["./quiz_service"]
# CMD ["tail", "-f", "/dev/null"]
