// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: gRPC/gRPC_Code/UserData/UserService.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []string               `protobuf:"bytes,1,rep,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsRequest) Reset() {
	*x = GetUserDetailsRequest{}
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRequest) ProtoMessage() {}

func (x *GetUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserDetailsRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetUserDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*UserProfile         `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsResponse) Reset() {
	*x = GetUserDetailsResponse{}
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsResponse) ProtoMessage() {}

func (x *GetUserDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDetailsResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserDetailsResponse) GetProfiles() []*UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UserRole      string                 `protobuf:"bytes,4,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

var File_gRPC_gRPC_Code_UserData_UserService_proto protoreflect.FileDescriptor

const file_gRPC_gRPC_Code_UserData_UserService_proto_rawDesc = "" +
	"\n" +
	")gRPC/gRPC_Code/UserData/UserService.proto\x12\x04User\"/\n" +
	"\x15GetUserDetailsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x03(\tR\x06userId\"G\n" +
	"\x16GetUserDetailsResponse\x12-\n" +
	"\bprofiles\x18\x01 \x03(\v2\x11.User.UserProfileR\bprofiles\"s\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tuser_role\x18\x04 \x01(\tR\buserRole2[\n" +
	"\vUserService\x12L\n" +
	"\x0fGetUsersProfile\x12\x1b.User.GetUserDetailsRequest\x1a\x1c.User.GetUserDetailsResponseB\"Z Progression_service_GO/gRPC;userb\x06proto3"

var (
	file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescOnce sync.Once
	file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescData []byte
)

func file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescGZIP() []byte {
	file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescOnce.Do(func() {
		file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_gRPC_Code_UserData_UserService_proto_rawDesc), len(file_gRPC_gRPC_Code_UserData_UserService_proto_rawDesc)))
	})
	return file_gRPC_gRPC_Code_UserData_UserService_proto_rawDescData
}

var file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gRPC_gRPC_Code_UserData_UserService_proto_goTypes = []any{
	(*GetUserDetailsRequest)(nil),  // 0: User.GetUserDetailsRequest
	(*GetUserDetailsResponse)(nil), // 1: User.GetUserDetailsResponse
	(*UserProfile)(nil),            // 2: User.UserProfile
}
var file_gRPC_gRPC_Code_UserData_UserService_proto_depIdxs = []int32{
	2, // 0: User.GetUserDetailsResponse.profiles:type_name -> User.UserProfile
	0, // 1: User.UserService.GetUsersProfile:input_type -> User.GetUserDetailsRequest
	1, // 2: User.UserService.GetUsersProfile:output_type -> User.GetUserDetailsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gRPC_gRPC_Code_UserData_UserService_proto_init() }
func file_gRPC_gRPC_Code_UserData_UserService_proto_init() {
	if File_gRPC_gRPC_Code_UserData_UserService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_gRPC_Code_UserData_UserService_proto_rawDesc), len(file_gRPC_gRPC_Code_UserData_UserService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_gRPC_Code_UserData_UserService_proto_goTypes,
		DependencyIndexes: file_gRPC_gRPC_Code_UserData_UserService_proto_depIdxs,
		MessageInfos:      file_gRPC_gRPC_Code_UserData_UserService_proto_msgTypes,
	}.Build()
	File_gRPC_gRPC_Code_UserData_UserService_proto = out.File
	file_gRPC_gRPC_Code_UserData_UserService_proto_goTypes = nil
	file_gRPC_gRPC_Code_UserData_UserService_proto_depIdxs = nil
}
