FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY Course_Service/package.json ./Course_Service
# COPY shared-middleware/package.json ./shared-middleware

RUN npm i -g pnpm && pnpm install --filter course_service

COPY Course_Service ./Course_Service

COPY shared-middleware ./shared-middleware

WORKDIR /app/Course_Service

CMD [ "pnpm", "start" ]