// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: gRPC/protoFiles/course.proto

package CourseDetails

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDataRequest) Reset() {
	*x = CourseDataRequest{}
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDataRequest) ProtoMessage() {}

func (x *CourseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDataRequest.ProtoReflect.Descriptor instead.
func (*CourseDataRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_protoFiles_course_proto_rawDescGZIP(), []int{0}
}

func (x *CourseDataRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CourseDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseData    *CourseDetails         `protobuf:"bytes,1,opt,name=courseData,proto3" json:"courseData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDataResponse) Reset() {
	*x = CourseDataResponse{}
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDataResponse) ProtoMessage() {}

func (x *CourseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDataResponse.ProtoReflect.Descriptor instead.
func (*CourseDataResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_protoFiles_course_proto_rawDescGZIP(), []int{1}
}

func (x *CourseDataResponse) GetCourseData() *CourseDetails {
	if x != nil {
		return x.CourseData
	}
	return nil
}

type CourseDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetails) Reset() {
	*x = CourseDetails{}
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetails) ProtoMessage() {}

func (x *CourseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetails.ProtoReflect.Descriptor instead.
func (*CourseDetails) Descriptor() ([]byte, []int) {
	return file_gRPC_protoFiles_course_proto_rawDescGZIP(), []int{2}
}

func (x *CourseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseDetails) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CourseDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CourseDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CourseModuleDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseModuleDataRequest) Reset() {
	*x = CourseModuleDataRequest{}
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseModuleDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseModuleDataRequest) ProtoMessage() {}

func (x *CourseModuleDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseModuleDataRequest.ProtoReflect.Descriptor instead.
func (*CourseModuleDataRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_protoFiles_course_proto_rawDescGZIP(), []int{3}
}

func (x *CourseModuleDataRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type CourseModuleDataResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CompletionPercentage int32                  `protobuf:"varint,4,opt,name=completion_percentage,json=completionPercentage,proto3" json:"completion_percentage,omitempty"`
	CourseId             string                 `protobuf:"bytes,5,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CourseModuleDataResponse) Reset() {
	*x = CourseModuleDataResponse{}
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseModuleDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseModuleDataResponse) ProtoMessage() {}

func (x *CourseModuleDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_protoFiles_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseModuleDataResponse.ProtoReflect.Descriptor instead.
func (*CourseModuleDataResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_protoFiles_course_proto_rawDescGZIP(), []int{4}
}

func (x *CourseModuleDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseModuleDataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseModuleDataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseModuleDataResponse) GetCompletionPercentage() int32 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

func (x *CourseModuleDataResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

var File_gRPC_protoFiles_course_proto protoreflect.FileDescriptor

const file_gRPC_protoFiles_course_proto_rawDesc = "" +
	"\n" +
	"\x1cgRPC/protoFiles/course.proto\x12\x06Course\"0\n" +
	"\x11CourseDataRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"K\n" +
	"\x12CourseDataResponse\x125\n" +
	"\n" +
	"courseData\x18\x01 \x01(\v2\x15.Course.CourseDetailsR\n" +
	"courseData\"\xb8\x01\n" +
	"\rCourseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"6\n" +
	"\x17CourseModuleDataRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"\xb4\x01\n" +
	"\x18CourseModuleDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\x15completion_percentage\x18\x04 \x01(\x05R\x14completionPercentage\x12\x1b\n" +
	"\tcourse_id\x18\x05 \x01(\tR\bcourseId2\xb1\x01\n" +
	"\rCourseService\x12F\n" +
	"\rGetCourseData\x12\x19.Course.CourseDataRequest\x1a\x1a.Course.CourseDataResponse\x12X\n" +
	"\x13GetCourseModuleData\x12\x1f.Course.CourseModuleDataRequest\x1a .Course.CourseModuleDataResponseB5Z3Quiz_service_go/gRPC/gRPC_Code/Course;CourseDetailsb\x06proto3"

var (
	file_gRPC_protoFiles_course_proto_rawDescOnce sync.Once
	file_gRPC_protoFiles_course_proto_rawDescData []byte
)

func file_gRPC_protoFiles_course_proto_rawDescGZIP() []byte {
	file_gRPC_protoFiles_course_proto_rawDescOnce.Do(func() {
		file_gRPC_protoFiles_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_protoFiles_course_proto_rawDesc), len(file_gRPC_protoFiles_course_proto_rawDesc)))
	})
	return file_gRPC_protoFiles_course_proto_rawDescData
}

var file_gRPC_protoFiles_course_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gRPC_protoFiles_course_proto_goTypes = []any{
	(*CourseDataRequest)(nil),        // 0: Course.CourseDataRequest
	(*CourseDataResponse)(nil),       // 1: Course.CourseDataResponse
	(*CourseDetails)(nil),            // 2: Course.CourseDetails
	(*CourseModuleDataRequest)(nil),  // 3: Course.CourseModuleDataRequest
	(*CourseModuleDataResponse)(nil), // 4: Course.CourseModuleDataResponse
}
var file_gRPC_protoFiles_course_proto_depIdxs = []int32{
	2, // 0: Course.CourseDataResponse.courseData:type_name -> Course.CourseDetails
	0, // 1: Course.CourseService.GetCourseData:input_type -> Course.CourseDataRequest
	3, // 2: Course.CourseService.GetCourseModuleData:input_type -> Course.CourseModuleDataRequest
	1, // 3: Course.CourseService.GetCourseData:output_type -> Course.CourseDataResponse
	4, // 4: Course.CourseService.GetCourseModuleData:output_type -> Course.CourseModuleDataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gRPC_protoFiles_course_proto_init() }
func file_gRPC_protoFiles_course_proto_init() {
	if File_gRPC_protoFiles_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_protoFiles_course_proto_rawDesc), len(file_gRPC_protoFiles_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_protoFiles_course_proto_goTypes,
		DependencyIndexes: file_gRPC_protoFiles_course_proto_depIdxs,
		MessageInfos:      file_gRPC_protoFiles_course_proto_msgTypes,
	}.Build()
	File_gRPC_protoFiles_course_proto = out.File
	file_gRPC_protoFiles_course_proto_goTypes = nil
	file_gRPC_protoFiles_course_proto_depIdxs = nil
}
